import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import {CartProvider} from "@/context/CartContext";
import {AuthProvider} from "@/context/AuthContext";
import {Toaster} from "react-hot-toast";
import {CatalogProvider} from "@/app/catalog/catalog-context";
import {getProductTypes} from "@/app/catalog/catalog";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const productTypes = getProductTypes();
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
        <CatalogProvider productTypes={productTypes}>
            <AuthProvider>
                <CartProvider>
                    <Header/>
                    <main className="flex-grow">{children}</main>
                    <Footer/>
                    <Toaster
                        position="bottom-right"
                        toastOptions={{
                            style: {
                                background: "#2F4156",
                                color: "#fff",
                                padding: "16px",
                                fontSize: "1.125rem",
                                maxWidth: "500px",
                            },
                            success: {
                                iconTheme: {
                                    primary: "#567C8D",
                                    secondary: "#fff",
                                },
                            },
                        }}
                    />
                </CartProvider>
            </AuthProvider>
        </CatalogProvider>
        </body>
        </html>
    );
}
